# Generated by Django 2.1 on 2019-08-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('batch_id', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('batch_id', models.IntegerField()),
                ('cado_id', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_color', models.CharField(max_length=255)),
                ('initial_dense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_projected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Decline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('cado_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('projected_dense', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
